name: Noop

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  verify_and_test:
    name: Verify and Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'noop'
